services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: studytracker
      POSTGRES_USER: studytracker
      POSTGRES_PASSWORD: studytracker
    ports:
      - "${STUDYTRACKER_DB_PORT:-5436}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web-fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.web-fastapi
    environment:
      DATABASE_URL: postgresql://studytracker:studytracker@db:5432/studytracker
    depends_on:
      - db
    ports:
      - "${STUDYTRACKER_APP_PORT:-8035}:8000"

  web-fastapi-env:
    build:
      context: .
      dockerfile: docker/Dockerfile.web-fastapi
    environment:
      - .env
    depends_on:
      - db
    profiles: ["env"]
    ports:
      - "${STUDYTRACKER_ENV_APP_PORT:-8036}:8000"

volumes:
  db-data:
  
